// <auto-generated />
using System;
using CompanySystem.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompanySystem.Data.Migrations
{
    [DbContext(typeof(CompanySystemDbContext))]
    [Migration("20250731101306_RemoveManagerIdFromDepartment")]
    partial class RemoveManagerIdFromDepartment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CompanySystem.Data.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("DepartmentName");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 7, 31, 10, 13, 4, 890, DateTimeKind.Utc).AddTicks(6999),
                            DepartmentName = "Human Resources",
                            IsDeleted = false
                        },
                        new
                        {
                            DepartmentId = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 7, 31, 10, 13, 4, 890, DateTimeKind.Utc).AddTicks(7001),
                            DepartmentName = "Information Technology",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("CompanySystem.Data.Models.MainPageContent", b =>
                {
                    b.Property<int>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ContentId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ContentId");

                    b.HasIndex("SectionName");

                    b.ToTable("MainPageContents");

                    b.HasData(
                        new
                        {
                            ContentId = 1,
                            Content = "We are a leading company in our industry, committed to excellence and innovation.",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 7, 31, 10, 13, 4, 890, DateTimeKind.Utc).AddTicks(7089),
                            IsDeleted = false,
                            SectionName = "Overview",
                            Title = "Welcome to Our Company"
                        },
                        new
                        {
                            ContentId = 2,
                            Content = "Founded in 2020, we have been providing exceptional services to our clients worldwide.",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 7, 31, 10, 13, 4, 890, DateTimeKind.Utc).AddTicks(7091),
                            IsDeleted = false,
                            SectionName = "AboutUs",
                            Title = "About Our Company"
                        },
                        new
                        {
                            ContentId = 3,
                            Content = "We offer a comprehensive range of professional services including consulting and development.",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 7, 31, 10, 13, 4, 890, DateTimeKind.Utc).AddTicks(7093),
                            IsDeleted = false,
                            SectionName = "Services",
                            Title = "Our Professional Services"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
